import antfu from '@antfu/eslint-config'

export default antfu(
  {
    typescript: true,
    vue: true,
    ignores: [
      '_archive',
      '**/_archive/**',
      '.*',
      '**/.*/**',
      '*.json',
      '**/*.json/**',
      '*.local',
      '**/*.local/**',
      '*.log',
      '**/*.log/**',
      '*.wasm.js',
      '**/*.wasm.js/**',
      '*.mjs',
      '**/*.mjs/**',
      '*.cjs',
      '**/*.cjs/**',
      'bg.jpg',
      '**/bg.jpg/**',
      'build',
      '**/build/**',
      'coverage',
      '**/coverage/**',
      'data',
      '**/data/**',
      'dist',
      '**/dist/**',
      'dist_*',
      '**/dist_*/**',
      'dist_macos',
      '**/dist_macos/**',
      'dist_electron',
      '**/dist_electron/**',
      'docker',
      '**/docker/**',
      'geoip',
      '**/geoip/**',
      'help',
      '**/help/**',
      'internal',
      '**/internal/**',
      'legacy',
      '**/legacy/**',
      'logs',
      '**/logs/**',
      'node_modules',
      '**/node_modules/**',
      'npm-debug.log',
      '**/npm-debug.log/**',
      'package-lock.json',
      '**/package-lock.json/**',
      'pnpm-lock.yaml',
      '**/pnpm-lock.yaml/**',
      'public',
      '**/public/**',
      'scripts',
      '**/scripts/**',
      'tmp',
      '**/tmp/**',
      'video',
      '**/video/**',
      'wiki',
      '**/wiki/**',
      'www',
      '**/www/**',
      'yarn-error.log',
      '**/yarn-error.log/**',
      'vite.config.ts',
      '**/vite.config.ts/**',
      'vitest*',
      '**/vitest*/**',
      'zerva-vite/ssr-vue/*',
      'zerva-vite/ssr-vue/*/**',
      'examples/vite-ssr/*',
      'examples/vite-ssr/*/**'],

    // ignores: [
    //   'dist',
    //   'node_modules',
    //   'build',
    //   'tmp',
    //   'demos',
    //   'coverage',
    //   '_archive',
    //   '*.spec.*',
    //   'vitest.config.ts',
    // ],
  },
  {},
  {
    rules: {
      'unused-imports/no-unused-vars': 'off',
      'antfu/consistent-list-newline': 'off',
      'eslint-disable-unused-imports/no-unused-imports': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
    },
  },
)
