import antfu from '@antfu/eslint-config'

export default antfu(
  {
    // typescript: {
    //   tsconfigPath: './tsconfig.json',
    //   // ignores,
    // },
    typescript: true,
    vue: true,
    ignores: [
      '*.md',
      '**/*.md/**',
      '**/*.md',
      '_archive',
      '**/_archive/**',
      '.*',
      '**/.*/**',
      '*.json',
      '**/*.json/**',
      '*.local',
      '**/*.local/**',
      '*.log',
      '**/*.log/**',
      '*.wasm.js',
      '**/*.wasm.js/**',
      '*.mjs',
      '**/*.mjs/**',
      '*.cjs',
      '**/*.cjs/**',
      'bg.jpg',
      '**/bg.jpg/**',
      'build',
      '**/build/**',
      'coverage',
      '**/coverage/**',
      'data',
      '**/data/**',
      'dist',
      '**/dist/**',
      'dist_*',
      '**/dist_*/**',
      'docker',
      '**/docker/**',
      'geoip',
      '**/geoip/**',
      'help',
      '**/help/**',
      'internal',
      '**/internal/**',
      'legacy',
      '**/legacy/**',
      'logs',
      '**/logs/**',
      'node_modules',
      '**/node_modules/**',
      'npm-debug.log',
      '**/npm-debug.log/**',
      'package-lock.json',
      '**/package-lock.json/**',
      'pnpm-lock.yaml',
      '**/pnpm-lock.yaml/**',
      'public',
      '**/public/**',
      'scripts',
      '**/scripts/**',
      'tmp',
      '**/tmp/**',
      'video',
      '**/video/**',
      'wiki',
      '**/wiki/**',
      'www',
      '**/www/**',
      'yarn-error.log',
      '**/yarn-error.log/**',
      'vite.config.ts',
      '**/vite.config.ts/**',
      'vitest*',
      '**/vitest*/**',
      'zerva-vite/ssr-vue/*',
      'zerva-vite/ssr-vue/*/**',
      'examples/vite-ssr/*',
      'examples/vite-ssr/*/**',
      '**/.out.*',
      '.out.*',
    ],
  },
  {},
  {
    rules: {
      'unused-imports/no-unused-vars': 'off',
      'antfu/consistent-list-newline': 'off',
      'eslint-disable-unused-imports/no-unused-imports': 'off',
      'ts/no-unsafe-argument': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-call': 'off',
      'ts/no-unsafe-member-access': 'off',
      'ts/no-unsafe-return': 'off',
      'ts/restrict-template-expressions': 'off',
      // 'ts/require-await': 'off',
      // 'ts/no-misused-promises': 'off',
    },
  },
)
