packages:
  - zerva-*
  - examples/*
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
overrides:
  js-yaml@>=4.0.0 <4.1.1: ">=4.1.1"
  serialize-javascript@<=7.0.2: ">=7.0.3"
shellEmulator: true
