/* eslint-disable no-console */
import type { ChildProcess } from 'node:child_process'
import { spawn } from 'node:child_process'
import { chmod } from 'node:fs/promises'
import { normalize } from 'node:path'
import { chmodSync } from 'node:fs'
import type { BuildOptions, Plugin } from 'esbuild'
import { context } from 'esbuild'
import { yamlPlugin } from 'esbuild-plugin-yaml'

// @ts-expect-error xxx
import displayNotification from 'display-notification'
import type { ZervaConf } from './config'

export async function runMain(config: ZervaConf) {
  let zervaNodeProcess: ChildProcess | undefined
  // let zervaNodeProcessDidEndPromise: ((value?: unknown) => void) | undefined

  async function stopNode() {
    // console.log(`Zerva: Trigger stopping app ${zervaNodeProcess}\n`)

    if (zervaNodeProcess) {
      console.log('Zerva: Stopping app\n')

      // sic!
      // const _ = new Promise(resolve => (zervaNodeProcessDidEndPromise = resolve))

      zervaNodeProcess.kill('SIGTERM')
      // p.kill("SIGKILL")
      zervaNodeProcess = undefined
    }
  }

  async function startNode() {
    await stopNode()

    const cwd = process.cwd()
    const nodeArgs = [
      '--enable-source-maps',
      ...config.node,
      config.outfile,
    ]

    if (config.debug)
      console.info(`Zerva: Spawn node in ${cwd} with args:`, nodeArgs)

    zervaNodeProcess = spawn(
      process.execPath,
      nodeArgs,
      {
        cwd,
        stdio: 'inherit',
        env: {
          ...process.env,
          ZERVA_MODE: 'development',
          ZERVA_VERSION: config.version,
        },
      },
    )

    console.info('Zerva: Starting app')
    zervaNodeProcess.on('error', (err) => {
      console.error('Node process error:', err)
    })
    // zervaNodeProcess.on('close', (code) => {
    // console.info('Zerva: Node process close with code:', code)
    // if (zervaNodeProcessDidEndPromise) {
    //   zervaNodeProcessDidEndPromise()
    //   zervaNodeProcessDidEndPromise = undefined
    // }
    // })
    // zervaNodeProcess.on("exit", () => {
    //   console.info("Zerva: Node process exit.")
    // })
  }

  async function notifyError(error: any) {
    try {
      if (!config.build) {
        // https://www.npmjs.com/package/display-notification
        await displayNotification({
          subtitle: 'Zerva Build Error',
          text: error?.text ?? 'Error',
          sound: 'Bottle',
        })
      }
    }
    catch (err) { }
  }

  function toHumanReadableFilePath(path: string) {
    const p = normalize(path)
    const h = process.env.HOME
    if (h && p.startsWith(h))
      return `~${p.slice(h.length)}`

    return p
  }

  console.info(`Zerva: Building from "${toHumanReadableFilePath(config.entry)}"`)

  const plugins = [
    yamlPlugin({}),
  ]

  if (!config.build) {
    plugins.push({
      name: 'zerva-rebuild',
      setup(build) {
        build.onStart(stopNode)
        build.onEnd((result) => {
          if (result.errors?.length > 0) {
            console.log(`build ended with ${result.errors.length} errors`)
            void notifyError(result.errors?.[0])
            return
          }

          try {
            chmodSync(config.outfile, 0o755)
          }
          catch (err) { }
          void startNode()
        })

        build.onDispose(stopNode)
      },
    } as Plugin)
  }

  // Started from command line
  const buildConfig: BuildOptions = {
    bundle: true,
    platform: 'node',
    target: 'node16',
    format: config.esm ? 'esm' : 'cjs',
    entryPoints: [config.entry],
    legalComments: 'none',
    outfile: config.outfile,
    metafile: config.metafile,
    sourcemap: !config.build || config.sourcemap,
    jsxFactory: 'h',
    loader: {
      '.json': 'json',
      ...config.loader,
    },
    plugins,
    banner: {
      js: '/*\n\n    Generated by Zerva <https://github.com/holtwick/zerva>\n\n*/',
    },
    define: {
      // ZERVA_MODE: buildMode ? "production" : "development",
      'ZERVA_DEVELOPMENT': String(!config.build),
      'ZERVA_PRODUCTION': String(config.build),
      'ZERVA_VERSION': `"${config.version}"`,
      'process.env.ZERVA_DEVELOPMENT': String(!config.build),
      'process.env.ZERVA_PRODUCTION': String(config.build),
      'process.env.ZERVA_VERSION': `"${config.version}"`,
      ...config.define,
    } as any,
    minify: config.build,
    external: config.build
      ? ['esbuild', 'fs', 'fsevents', 'notifier', 'node-notifier', ...config.external]
      : ['esbuild', 'fs', 'fsevents', 'notifier', 'node-notifier', 'vite', ...config.external],
    ...config.esbuild,
  }

  if (config.debug)
    console.log('build =', buildConfig)

  // https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0170
  const buildContext = await context(buildConfig)

  if (!config.build) {
    console.info('Zerva: Watching...')
    await buildContext.watch()
    return
  }

  const result = buildContext.rebuild()
  result
    .then(async (r) => {
      try {
        await chmod(config.outfile, 0o755)
      }
      catch (err) { }

      console.info(`Zerva: Building to "${toHumanReadableFilePath(config.outfile)}" succeeded.`)
      await buildContext.dispose()
    })
    .catch((error: any) => {
      void notifyError(error)
    })
}
